### ISSUE TITLE
Hi, how do i install it?

### ISSUE THREAD

**Issue by webenadam** [Elec0/chrome-edge-workspaces#1]
Does it support saving multiple windows with there tabs? or just on window with his tabs?

Thanks!
Benjamin

**Comment by Comnenus** [comment]
I am also interested in how to install this.

**Comment by Elec0** [comment]
Sorry, this is still in development, so it's not available on the chrome store yet.

Thank you for the interest, though! Progress is still going steadily, so check back in every now and then, it'll be released eventually. 😄

**Comment by Elec0** [comment]
@webenadam @Comnenus I've just published the first (hopefully) working version: https://github.com/Elec0/chrome-edge-workspaces/releases/tag/v0.2.0-alpha

Note that it's an alpha, **not** a full release.

I would appreciate any bug reports, though.

**Comment by Comnenus** [comment]
Thank you!  However, When I load unpacked, it says the manifest file is missing or unreadable?  What am I doing wrong?  It is extracted and I am selecting that directory.

**Comment by Elec0** [comment]
Hm that's strange.
If you go into the extracted folder, you do see `manifest.json`, right?

What version of Chrome are you running? I'm on `Version 124.0.6367.208`.

**Comment by Comnenus** [comment]
I am on `Version 124.0.6367.208`.  There is a `public/manifest.json` but I get the same error if I point to that directory, or move manifest.json into the root.

**Comment by Elec0** [comment]
Ohh, you're downloading the whole repo.
Download the release, not the repo: https://github.com/Elec0/chrome-edge-workspaces/releases/tag/v0.2.0-alpha
