### ISSUE TITLE
Sync workspaces across account

### ISSUE THREAD

**Issue by Elec0** [Elec0/chrome-edge-workspaces#5]
It's pretty straightforward to store a copy of the `localData` in `syncStorage`. This should be done, to allow easy switching of computers without losing data.

Important note: Sync storage does have a save throttle on it, so a new mechanism to batch updates needs to be implemented.

**Comment by Elec0** [comment]
Turns out, it's not as simple as I thought.
When trying to save a sufficient set of workspaces, I get 
```
Error: QUOTA_BYTES_PER_ITEM quota exceeded
```

Because the entire workspace storage is stored in a single "item".
I don't know what counts as an "item", or how it's defined. Need to figure that out, then refactor `StorageHelper` to save things that way instead.

My thought is that each top-level key counts as an "item", which each of have a max of ~8kb.
So I'll probably have to redesign the entire storage structure. 😡

**Comment by clutterskull** [comment]
Having given this a lot of thought myself and after scouring for a workspace extension that isn't just tab sessions _and_ syncs (very rare), can I suggest you consider using a bookmark tree for storage? You'd get sync for free and it would work in basically every browser. I suppose there's would be some difficulty in watching for changes, but you've basically got very long string storage in the folder and bookmark names and could use some encoded hashing and just poll it for hydrating your WorkspaceStorage.

Just spitballing ideas. I'm considering options including rolling my own and I really don't want to have to. :laughing: 

For reference, this extension takes the bookmark approach in Chrome called [SpaceVibe](https://chromewebstore.google.com/detail/spacevibe/lbnkblgmenbcfmnielkhaiojeheplbjg), but it's poorly named for search and somewhat unpolished.

**Comment by asteele0** [comment]
Yes! I have had that idea as well, and even had a prototype during development.
At the time I was considering it as a replacement for the `localStorage`, but I think your idea of using it for cheap syncing is very good.

Something I think would be easy would be to just output the workspaces as bookmarks in folders and such. It wouldn't even have to sync, to start with, to be valuable.

**Comment by Elec0** [comment]
Yes! I have had that idea as well, and even had a prototype during development.
At the time I was considering it as a replacement for the `localStorage`, but I think your idea of using it for cheap syncing is very good.

Something I think would be easy would be to just output the workspaces as bookmarks in folders and such. It wouldn't even have to sync, to start with, to be valuable.

**Comment by clutterskull** [comment]
Oh, yeah, I kind of forget about that. Bookmarks, can be meddled with by the user which could be a problem, but if the structure is kept simple it means it's user editable and searchable.
